server: 
  port: 9020
spring: 
  application:  
    name: spacefafu-chat #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.15.128:3306/tensquare_chat?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
eureka:
 client:
  service-url:
   defaultZone: http://localhost:6868/eureka
 instance:
  prefer-ip-address: true
