server:
  port: 9006
spring:
  application:
    name: spacefafu-spit
  data:
    mongodb:
      host: 192.168.15.128
      database: spitdb
  redis:
    host: 192.168.15.128
  rabbitmq:
    host: 192.168.15.128
eureka:
 client:
  service-url:
   defaultZone: http://localhost:6868/eureka
 instance:
  prefer-ip-address: true
